base_url = "https://peterlyons.org"
generate_rss = true
compile_sass = true
highlight_code = false
build_search_index = false
title = "The Stretch of Vitality"

[extra]
# Put all your custom variables here
blog_title = "The Stretch of Vitality"
